version: '3.8'

services:
  workbench:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: workbench
    ports:
      - "8080:3000"
    env_file:
      - server/.env
    volumes:
      - ./_shared:/app/_shared
      - ./index.html:/app/index.html
    restart: unless-stopped
